server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luma?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      read-only: false
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 60
      minimum-idle: 10
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  cache:
    jcache:
      config: classpath:/cache/ehcache.xml
mybatis:
  type-aliases-package: io.github.isliqian.sys.mapper
  mapper-locations: classpath:mapper/*.xml

#flyway:
#  baseline-version: 1
#  enabled: true
#
#  locations: db/db/{vendor}
#  sql-db-prefix: V
#  sql-db-suffix: .sql